---
title: Gin-n-Tonic 2016
output:
  html_document:
    keep_md: yes
    toc: yes
---

Happy New Year of 2016!

<!--  Set the working directory to the repository's base directory; this assumes the report is nested inside of two directories.-->
```{r, echo=F, message=F} 
# cat("Working directory: ", getwd())
  library(knitr)
  opts_knit$set(root.dir='../../')  #Don't combine this call with any other chunk -especially one that uses file paths.
```

<!-- Set the report-wide options, and point to the external code file. -->
```{r set_options, echo=F}
# cat("Working directory: ", getwd())
opts_chunk$set(
  results    = 'show', 
  comment    = NA, 
  tidy       = FALSE,
  fig.width  = 4, 
  fig.height = 4, 
  fig.path   = 'figure-png/'
)
# dpi = 400,
# out.width = "650px", #This affects only the markdown, not the underlying png file.  The height will be scaled appropriately.

echoChunks <- FALSE
options(width=120) #So the output is 50% wider than the default.
read_chunk("./analysis/basic-mds/basic-mds.R") #This allows knitr to call chunks tagged in the underlying *.R file.
```

<!-- Load the sources.  Suppress the output when loading sources. --> 
```{r load_sources, echo=echoChunks, message=FALSE}
```

<!-- Load 'sourced' R files.  Suppress the output when loading packages. --> 
```{r load_packages, echo=echoChunks, message=FALSE}
```

<!-- Load any global functions and variables declared in the R file.  Suppress the output. --> 
```{r declare_globals, echo=echoChunks, results='show', message=FALSE}
```

<!-- Declare any global functions specific to a Rmd output.  Suppress the output. --> 
```{r, echo=echoChunks, message=FALSE}
#Put presentation-specific code in here.  It doesn't call a chunk in the codebehind file.
```

<!-- Load the datasets.   -->
```{r load_data, echo=echoChunks, results='show', message=FALSE}
```

<!-- Tweak the datasets.   -->
```{r tweak_data, echo=echoChunks, results='show', message=FALSE}
```


```{r define_mds_plotting, echo=echoChunks, message=TRUE}
```


```{r andrey, echo=echoChunks, message=TRUE, fig.width=7, fig.height=7}
input <- c(1,
           2, 1,
           3, 2, 1,
           3, 1, 2, 1,
           3, 4, 4, 5, 1)
g <- mds_scatter(input, 3.5)
g + ggtitle("Andrey")
```




```{r jessica, echo=echoChunks, message=TRUE, fig.width=7, fig.height=7}
input <- c(1,
           2, 1,
           3, 1, 1,
           1, 2, 3, 1,
           5, 4, 5, 1, 1)
g <- mds_scatter(input, 3.5)
g + ggtitle("Jessica")
```


```{r brandon, echo=echoChunks, message=TRUE, fig.width=7, fig.height=7}
input <- c(1,
           3, 1,
           4, 2, 1,
           3, 2, 1, 1,
           4, 5, 3, 4, 1)
g <- mds_scatter(input, 3.5)
g + ggtitle("Brandon")
```


```{r amanda, echo=echoChunks, message=TRUE, fig.width=7, fig.height=7}
input <- c(1,
           4, 1,
           4, 2, 1,
           3, 3, 1, 1,
           5, 5, 5, 4, 1)
g <- mds_scatter(input, 3.5)
g + ggtitle("Amanda")
```


```{r kate, echo=echoChunks, message=TRUE, fig.width=7, fig.height=7}
input <- c(1,
           1, 1,
           2, 2, 1,
           3, 4, 1, 1,
           5, 5, 5, 5, 1)
g <- mds_scatter(input, 3.5)
g + ggtitle("Kate")
```


```{r jason, echo=echoChunks, message=TRUE, fig.width=7, fig.height=7}
input <- c(1,
           1, 1,
           3, 3, 1,
           2, 3, 3, 1,
           5, 5, 3, 4, 1)
g <- mds_scatter(input, 3.5)
g + ggtitle("Jason")
```


```{r sasha, echo=echoChunks, message=TRUE, fig.width=7, fig.height=7}
input <- c(1,
           2, 1,
           1, 2, 1,
           3, 2, 1, 1,
           5, 4, 5, 5, 1)
g <- mds_scatter(input, 3.5)
g + ggtitle("Sasha")
```

```{r ken, echo=echoChunks, message=TRUE, fig.width=7, fig.height=7}
input <- c(1,
           3, 1,
           3, 3, 1,
           1, 2, 3, 1,
           5, 4, 5, 5, 1)
g <- mds_scatter(input, 3.5)
g + ggtitle("Ken")
```

# Session Information
For the sake of documentation and reproducibility, the current report was rendered on a system using the following software.

```{r session_info, echo=FALSE}
cat("Report rendered by", Sys.info()["user"], "at", strftime(Sys.time(), "%Y-%m-%d, %H:%M %z"))
sessionInfo()
```
